currencymate:
  bot:
    token: ${BOT_TOKEN}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db.bacxjchgkksxkjiesfcm.supabase.co:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
