version: '3.4'
services:
  currencymate:
    network_mode: host
    image: currencymate
    env_file:
      - .env
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      network: host