# Build
FROM maven:3-eclipse-temurin-22 AS builder
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests

# Run
FROM eclipse-temurin:22-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/CurrencyMate.jar .
CMD ["java", "-jar", "CurrencyMate.jar"]
