# Build
FROM maven:3-eclipse-temurin-22 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Use an openjdk 17 base image as the builder stage
FROM eclipse-temurin:22-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/CurrencyMate.jar .
CMD ["java", "-jar", "CurrencyMate.jar"]
