name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            vorobeyyyyyy/currency-mate:latest
            vorobeyyyyyy/currency-mate:${{ github.sha }}
          file: "docker/dockerfile"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem docker/docker-compose.yml ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOSTNAME }}:/deploy
          ssh -i private_key.pem ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOSTNAME }} "docker pull vorobeyyyyyy/currency-mate:latest && docker-compose -f /deploy/docker-compose.yml up -d"