name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            vorobeyyyyyy/currency-mate:latest
            vorobeyyyyyy/currency-mate:${{ github.sha }}
          file: "docker/dockerfile"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOSTNAME }}
      DEPLOY_PATH: deploy/currency-mate
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -p 8022 -i private_key.pem $REMOTE_HOST "mkdir $DEPLOY_PATH"
          scp -o StrictHostKeyChecking=no -P 8022 -i private_key.pem docker/docker-compose.yml $REMOTE_HOST:$DEPLOY_PATH
          ssh -o StrictHostKeyChecking=no -p 8022 -i private_key.pem $REMOTE_HOST "echo "${{ secrets.ENV }}" > $DEPLOY_PATH/.env"
          ssh -o StrictHostKeyChecking=no -p 8022 -i private_key.pem $REMOTE_HOST "docker compose -f $DEPLOY_PATH/docker-compose.yml up && docker compose -f $DEPLOY_PATH/docker-compose.yml up -d"